# Generated by Django 6.0.7 on 2026-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('RA', models.IntegerField(primary_key=True, serialize=False, verbose_name='Digite sua RA')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('nascimento', models.DateField(verbose_name='Digite sua idade')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Digite o codigo!')),
                ('nomecurso', models.CharField(verbose_name='Digite o nome do curso')),
                ('cargarHoraria', models.DateTimeField(verbose_name='Digite a carga horária do curso')),
                ('datainicio', models.DateField(verbose_name='Digite ínicio')),
                ('dataTermino', models.DateField(verbose_name='Digite Término')),
            ],
        ),
    ]
