# Generated by Django 6.0.7 on 2026-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_aluno_id_alter_aluno_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='RA',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Digite sua RA'),
        ),
    ]
