# Generated by Django 6.0.7 on 2026-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_remove_aluno_id_alter_aluno_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nomecurso',
            field=models.CharField(max_length=100, verbose_name='Digite o nome do curso'),
        ),
    ]
