# Generated by Django 6.0.7 on 2026-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0004_alter_curso_nomecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cargarHoraria',
            field=models.IntegerField(verbose_name='Digite a carga horária do curso'),
        ),
    ]
